#!/usr/bin/env bash


SERVE_IP=$(ifconfig en0 | grep "inet " | awk '{print $2}')
echo "SERVE IP: http://${SERVE_IP}"

VENV="vblogenv"
if [ -d "$VENV" ]; then
    source "$VENV/bin/activate"
   mkdocs serve -a 0.0.0.0:80
else
    ./setup
fi

